version: '3'
services: 
  db:
    image: postgres
    environment:
      POSTGRES_DB: db_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tajna
      PGDATA: /tmp
    volumes:
      - ./db/sql/user/1_create.sql:/docker-entrypoint-initdb.d/1-create_user.sql
      - ./db/sql/item/2_create.sql:/docker-entrypoint-initdb.d/2-create_item.sql
    ports:
      - 5432:5432
    networks: 
      apinetwork:
  rest:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/github.com/ajdinahmetovic/go-rest
    ports:
      - "3000:3000"
    depends_on: 
      - service
    links:
      - db
    networks: 
      apinetwork:
  service:
    build: .
    command: ["go", "run", "."]
    volumes:
      - .:/go/src/github.com/ajdinahmetovic/item-service/server
    ports:
      - "4040:4040"
    depends_on: 
      - db
    links:
      - db
    networks: 
      apinetwork:
networks:
  apinetwork:
    driver: bridge